### PR TITLE
Remove platform APIs fallback

### PR DESCRIPTION
**Pull request by aethanyc**
This PR ports two commit from my icu4x segmenter branch back, and fixed some warnings. 

The motivation is that it's easier to removed platform APIs in uax14_rs and redo the importing than reworking recent commit in uax14_rs in my icu4x branch.

### CODE REVIEW

**Comment by aethanyc** [comment]
@makotokato r?

**Comment by aethanyc** [comment]
If uax14_rs's master branch still wants the platform APIs, is it OK to create to special branch that doesn't have these APIs, which is suitable to integrate into icu4x?

**Comment by makotokato** [comment]
> If uax14_rs's master branch still wants the platform APIs, is it OK to create to special branch that doesn't have these APIs, which is suitable to integrate into icu4x?

I should remove platform code from master branch.

**Comment by aethanyc** [comment]
Thanks for accepting this PR!

**Pull request merged**
